### ISSUE TITLE
Missing extract-text-webpack-plugin

### ISSUE THREAD

**Issue by mariolo1985** [DAVFoundation/xplore#165]
`extract-text-webpack-plugin` is being used in [webpack.prod.js](https://github.com/DAVFoundation/xplore/blob/master/webpack.prod.js#L9) and [webpack.common.js](https://github.com/DAVFoundation/xplore/blob/master/webpack.common.js#L3) but is not included as a [dependency](https://github.com/DAVFoundation/xplore/blob/master/package.json#L22).

## Expected Behavior

When installing dependencies, `extract-text-webpack-plugin` should be installed as a devDependencies.

## Current Behavior

```
Error: Cannot find module 'extract-text-webpack-plugin'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\MLo\Documents\MLo\Projects\dav\realRepos\xplore\webpack.common.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```
## Possible Solution

Include `extract-text-webpack-plugin` as a dependecy.

## Steps to Reproduce (for bugs)

1. Run `npm install`
2. Run `npm run build`

## Context

Unable to run build command.

## Your Environment

* Version used:
* Environment name and version (e.g. Node 7.3.12): Node 10.15.0 NPM 6.6.0
* Server type and version: 
* Operating System and version: Windows 8.1
* Link to your project:

**Comment by sureife** [comment]
Hi, I am available to fix this one. Should I go ahead?

**Comment by mariolo1985** [comment]
Hello @sureife - if you are still available, please go ahead 👍 thanks!

**Comment by sureife** [comment]
Thanks @mariolo1985

**Comment by TalAter** [comment]
@sureife 
Are you still interested in fixing this one?
You can also go ahead and tackle #163 and #147 if you want
