### ISSUE TITLE
webpack.dev.js has syntax errors

### ISSUE THREAD

**Issue by mariolo1985** [DAVFoundation/xplore#166]
```
xplore\webpack.dev.js:30
});
^

SyntaxError: Unexpected token }
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```
## Expected Behavior

To run `npm run start` successfully

## Current Behavior

Errors with a `Unexpected token` message

## Possible Solution

Resolve block brackets.

## Steps to Reproduce (for bugs)

1. Run `npm install`
2. Run `npm run start`

## Context

Unable to start dev server.

## Your Environment

* Version used:
* Environment name and version (e.g. Node 7.3.12): Node 10.15.0 NPM 6.6.0
* Server type and version:
* Operating System and version: Windows 8.1
* Link to your project:

**Comment by TalAter** [comment]
Fixed in #167
